drop database if exists dac1;
drop database if exists dac2;
drop database if exists dac3;
drop database if exists dac4;
drop database if exists dac5;
drop database if exists dac6;
drop database if exists dac7;
drop database if exists dac8;
drop database if exists dac9;
drop database if exists dac10;

drop database if exists dac11;
drop database if exists dac12;
drop database if exists dac13;
drop database if exists dac14;
drop database if exists dac15;
drop database if exists dac16;
drop database if exists dac17;
drop database if exists dac18;
drop database if exists dac19;
drop database if exists dac20;

drop database if exists dac21;
drop database if exists dac22;
drop database if exists dac23;
drop database if exists dac24;
drop database if exists dac25;
drop database if exists dac26;
drop database if exists dac27;
drop database if exists dac28;
drop database if exists dac29;
drop database if exists dac30;

drop database if exists dac31;
drop database if exists dac32;
drop database if exists dac33;
drop database if exists dac34;
drop database if exists dac35;
drop database if exists dac36;
drop database if exists dac37;
drop database if exists dac38;
drop database if exists dac39;
drop database if exists dac40;

drop database if exists dac41;
drop database if exists dac42;
drop database if exists dac43;
drop database if exists dac44;
drop database if exists dac45;
drop database if exists dac46;
drop database if exists dac47;
drop database if exists dac48;
drop database if exists dac49;
drop database if exists dac50;

drop database if exists dac51;
drop database if exists dac52;
drop database if exists dac53;
drop database if exists dac54;
drop database if exists dac55;
drop database if exists dac56;
drop database if exists dac57;
drop database if exists dac58;
drop database if exists dac59;
drop database if exists dac60;

drop database if exists dac1_CAMPUS;
drop database if exists dac2_CAMPUS;
drop database if exists dac3_CAMPUS;
drop database if exists dac4_CAMPUS;
drop database if exists dac5_CAMPUS;
drop database if exists dac6_CAMPUS;
drop database if exists dac7_CAMPUS;
drop database if exists dac8_CAMPUS;
drop database if exists dac9_CAMPUS;
drop database if exists dac10_CAMPUS;

drop database if exists dac11_CAMPUS;
drop database if exists dac12_CAMPUS;
drop database if exists dac13_CAMPUS;
drop database if exists dac14_CAMPUS;
drop database if exists dac15_CAMPUS;
drop database if exists dac16_CAMPUS;
drop database if exists dac17_CAMPUS;
drop database if exists dac18_CAMPUS;
drop database if exists dac19_CAMPUS;
drop database if exists dac20_CAMPUS;

drop database if exists dac21_CAMPUS;
drop database if exists dac22_CAMPUS;
drop database if exists dac23_CAMPUS;
drop database if exists dac24_CAMPUS;
drop database if exists dac25_CAMPUS;
drop database if exists dac26_CAMPUS;
drop database if exists dac27_CAMPUS;
drop database if exists dac28_CAMPUS;
drop database if exists dac29_CAMPUS;
drop database if exists dac30_CAMPUS;

drop database if exists dac31_CAMPUS;
drop database if exists dac32_CAMPUS;
drop database if exists dac33_CAMPUS;
drop database if exists dac34_CAMPUS;
drop database if exists dac35_CAMPUS;
drop database if exists dac36_CAMPUS;
drop database if exists dac37_CAMPUS;
drop database if exists dac38_CAMPUS;
drop database if exists dac39_CAMPUS;
drop database if exists dac40_CAMPUS;

drop database if exists dac41_CAMPUS;
drop database if exists dac42_CAMPUS;
drop database if exists dac43_CAMPUS;
drop database if exists dac44_CAMPUS;
drop database if exists dac45_CAMPUS;
drop database if exists dac46_CAMPUS;
drop database if exists dac47_CAMPUS;
drop database if exists dac48_CAMPUS;
drop database if exists dac49_CAMPUS;
drop database if exists dac50_CAMPUS;

drop database if exists dac51_CAMPUS;
drop database if exists dac52_CAMPUS;
drop database if exists dac53_CAMPUS;
drop database if exists dac54_CAMPUS;
drop database if exists dac55_CAMPUS;
drop database if exists dac56_CAMPUS;
drop database if exists dac57_CAMPUS;
drop database if exists dac58_CAMPUS;
drop database if exists dac59_CAMPUS;
drop database if exists dac60_CAMPUS;


drop user if exists dac1 ;
drop user if exists dac2 ;
drop user if exists dac3 ;
drop user if exists dac4 ;
drop user if exists dac5 ;
drop user if exists dac6 ;
drop user if exists dac7 ;
drop user if exists dac8 ;
drop user if exists dac9 ;
drop user if exists dac10;

drop user if exists dac11;
drop user if exists dac12;
drop user if exists dac13;
drop user if exists dac14;
drop user if exists dac15;
drop user if exists dac16;
drop user if exists dac17;
drop user if exists dac18;
drop user if exists dac19;
drop user if exists dac20;

drop user if exists dac21;
drop user if exists dac22;
drop user if exists dac23;
drop user if exists dac24;
drop user if exists dac25;
drop user if exists dac26;
drop user if exists dac27;
drop user if exists dac28;
drop user if exists dac29;
drop user if exists dac30;

drop user if exists dac31;
drop user if exists dac32;
drop user if exists dac33;
drop user if exists dac34;
drop user if exists dac35;
drop user if exists dac36;
drop user if exists dac37;
drop user if exists dac38;
drop user if exists dac39;
drop user if exists dac40;

drop user if exists dac41;
drop user if exists dac42;
drop user if exists dac43;
drop user if exists dac44;
drop user if exists dac45;
drop user if exists dac46;
drop user if exists dac47;
drop user if exists dac48;
drop user if exists dac49;
drop user if exists dac50;
	 
drop user if exists dac51;
drop user if exists dac52;
drop user if exists dac53;
drop user if exists dac54;
drop user if exists dac55;
drop user if exists dac56;
drop user if exists dac57;
drop user if exists dac58;
drop user if exists dac59;
drop user if exists dac60;

create database if NOT exists dac1;
create database if NOT exists dac2;
create database if NOT exists dac3;
create database if NOT exists dac4;
create database if NOT exists dac5;
create database if NOT exists dac6;
create database if NOT exists dac7;
create database if NOT exists dac8;
create database if NOT exists dac9;
create database if NOT exists dac10;

create database if NOT exists dac11;
create database if NOT exists dac12;
create database if NOT exists dac13;
create database if NOT exists dac14;
create database if NOT exists dac15;
create database if NOT exists dac16;
create database if NOT exists dac17;
create database if NOT exists dac18;
create database if NOT exists dac19;
create database if NOT exists dac20;

create database if NOT exists dac21;
create database if NOT exists dac22;
create database if NOT exists dac23;
create database if NOT exists dac24;
create database if NOT exists dac25;
create database if NOT exists dac26;
create database if NOT exists dac27;
create database if NOT exists dac28;
create database if NOT exists dac29;
create database if NOT exists dac30;

create database if NOT exists dac31;
create database if NOT exists dac32;
create database if NOT exists dac33;
create database if NOT exists dac34;
create database if NOT exists dac35;
create database if NOT exists dac36;
create database if NOT exists dac37;
create database if NOT exists dac38;
create database if NOT exists dac39;
create database if NOT exists dac40;

create database if NOT exists dac41;
create database if NOT exists dac42;
create database if NOT exists dac43;
create database if NOT exists dac44;
create database if NOT exists dac45;
create database if NOT exists dac46;
create database if NOT exists dac47;
create database if NOT exists dac48;
create database if NOT exists dac49;
create database if NOT exists dac50;

create database if NOT exists dac51;
create database if NOT exists dac52;
create database if NOT exists dac53;
create database if NOT exists dac54;
create database if NOT exists dac55;
create database if NOT exists dac56;
create database if NOT exists dac57;
create database if NOT exists dac58;
create database if NOT exists dac59;
create database if NOT exists dac60;

create database if NOT exists dac1_CAMPUS;
create database if NOT exists dac2_CAMPUS;
create database if NOT exists dac3_CAMPUS;
create database if NOT exists dac4_CAMPUS;
create database if NOT exists dac5_CAMPUS;
create database if NOT exists dac6_CAMPUS;
create database if NOT exists dac7_CAMPUS;
create database if NOT exists dac8_CAMPUS;
create database if NOT exists dac9_CAMPUS;
create database if NOT exists dac10_CAMPUS;

create database if NOT exists dac11_CAMPUS;
create database if NOT exists dac12_CAMPUS;
create database if NOT exists dac13_CAMPUS;
create database if NOT exists dac14_CAMPUS;
create database if NOT exists dac15_CAMPUS;
create database if NOT exists dac16_CAMPUS;
create database if NOT exists dac17_CAMPUS;
create database if NOT exists dac18_CAMPUS;
create database if NOT exists dac19_CAMPUS;
create database if NOT exists dac20_CAMPUS;

create database if NOT exists dac21_CAMPUS;
create database if NOT exists dac22_CAMPUS;
create database if NOT exists dac23_CAMPUS;
create database if NOT exists dac24_CAMPUS;
create database if NOT exists dac25_CAMPUS;
create database if NOT exists dac26_CAMPUS;
create database if NOT exists dac27_CAMPUS;
create database if NOT exists dac28_CAMPUS;
create database if NOT exists dac29_CAMPUS;
create database if NOT exists dac30_CAMPUS;

create database if NOT exists dac31_CAMPUS;
create database if NOT exists dac32_CAMPUS;
create database if NOT exists dac33_CAMPUS;
create database if NOT exists dac34_CAMPUS;
create database if NOT exists dac35_CAMPUS;
create database if NOT exists dac36_CAMPUS;
create database if NOT exists dac37_CAMPUS;
create database if NOT exists dac38_CAMPUS;
create database if NOT exists dac39_CAMPUS;
create database if NOT exists dac40_CAMPUS;

create database if NOT exists dac41_CAMPUS;
create database if NOT exists dac42_CAMPUS;
create database if NOT exists dac43_CAMPUS;
create database if NOT exists dac44_CAMPUS;
create database if NOT exists dac45_CAMPUS;
create database if NOT exists dac46_CAMPUS;
create database if NOT exists dac47_CAMPUS;
create database if NOT exists dac48_CAMPUS;
create database if NOT exists dac49_CAMPUS;
create database if NOT exists dac50_CAMPUS;

create database if NOT exists dac51_CAMPUS;
create database if NOT exists dac52_CAMPUS;
create database if NOT exists dac53_CAMPUS;
create database if NOT exists dac54_CAMPUS;
create database if NOT exists dac55_CAMPUS;
create database if NOT exists dac56_CAMPUS;
create database if NOT exists dac57_CAMPUS;
create database if NOT exists dac58_CAMPUS;
create database if NOT exists dac59_CAMPUS;
create database if NOT exists dac60_CAMPUS;

create user 'dac1'@'%' identified by 'welcome';
create user 'dac2'@'%' identified by 'welcome';
create user 'dac3'@'%' identified by 'welcome';
create user 'dac4'@'%' identified by 'welcome';
create user 'dac5'@'%' identified by 'welcome';
create user 'dac6'@'%' identified by 'welcome';
create user 'dac7'@'%' identified by 'welcome';
create user 'dac8'@'%' identified by 'welcome';
create user 'dac9'@'%' identified by 'welcome';
create user 'dac10'@'%' identified by 'welcome';

create user 'dac11'@'%' identified by 'welcome';
create user 'dac12'@'%' identified by 'welcome';
create user 'dac13'@'%' identified by 'welcome';
create user 'dac14'@'%' identified by 'welcome';
create user 'dac15'@'%' identified by 'welcome';
create user 'dac16'@'%' identified by 'welcome';
create user 'dac17'@'%' identified by 'welcome';
create user 'dac18'@'%' identified by 'welcome';
create user 'dac19'@'%' identified by 'welcome';
create user 'dac20'@'%' identified by 'welcome';
             			 
create user 'dac21'@'%' identified by 'welcome';
create user 'dac22'@'%' identified by 'welcome';
create user 'dac23'@'%' identified by 'welcome';
create user 'dac24'@'%' identified by 'welcome';
create user 'dac25'@'%' identified by 'welcome';
create user 'dac26'@'%' identified by 'welcome';
create user 'dac27'@'%' identified by 'welcome';
create user 'dac28'@'%' identified by 'welcome';
create user 'dac29'@'%' identified by 'welcome';
create user 'dac30'@'%' identified by 'welcome';	
			 
create user 'dac31'@'%' identified by 'welcome';
create user 'dac32'@'%' identified by 'welcome';
create user 'dac33'@'%' identified by 'welcome';
create user 'dac34'@'%' identified by 'welcome';
create user 'dac35'@'%' identified by 'welcome';
create user 'dac36'@'%' identified by 'welcome';
create user 'dac37'@'%' identified by 'welcome';
create user 'dac38'@'%' identified by 'welcome';
create user 'dac39'@'%' identified by 'welcome';
create user 'dac40'@'%' identified by 'welcome';
			 
create user 'dac41'@'%' identified by 'welcome';
create user 'dac42'@'%' identified by 'welcome';
create user 'dac43'@'%' identified by 'welcome';
create user 'dac44'@'%' identified by 'welcome';
create user 'dac45'@'%' identified by 'welcome';
create user 'dac46'@'%' identified by 'welcome';
create user 'dac47'@'%' identified by 'welcome';
create user 'dac48'@'%' identified by 'welcome';
create user 'dac49'@'%' identified by 'welcome';
create user 'dac50'@'%' identified by 'welcome';

create user 'dac51'@'%' identified by 'welcome';
create user 'dac52'@'%' identified by 'welcome';
create user 'dac53'@'%' identified by 'welcome';
create user 'dac54'@'%' identified by 'welcome';
create user 'dac55'@'%' identified by 'welcome';
create user 'dac56'@'%' identified by 'welcome';
create user 'dac57'@'%' identified by 'welcome';
create user 'dac58'@'%' identified by 'welcome';
create user 'dac59'@'%' identified by 'welcome';
create user 'dac60'@'%' identified by 'welcome';			 

grant all privileges on dac1.* to 'dac1'@'%';
grant all privileges on dac2.* to 'dac2'@'%';
grant all privileges on dac3.* to 'dac3'@'%';
grant all privileges on dac4.* to 'dac4'@'%';
grant all privileges on dac5.* to 'dac5'@'%';
grant all privileges on dac6.* to 'dac6'@'%';
grant all privileges on dac7.* to 'dac7'@'%';
grant all privileges on dac8.* to 'dac8'@'%';
grant all privileges on dac9.* to 'dac9'@'%';
grant all privileges on dac10.* to 'dac10'@'%';
		 
grant all privileges on dac11.* to 'dac11'@'%';
grant all privileges on dac12.* to 'dac12'@'%';
grant all privileges on dac13.* to 'dac13'@'%';
grant all privileges on dac14.* to 'dac14'@'%';
grant all privileges on dac15.* to 'dac15'@'%';
grant all privileges on dac16.* to 'dac16'@'%';
grant all privileges on dac17.* to 'dac17'@'%';
grant all privileges on dac18.* to 'dac18'@'%';
grant all privileges on dac19.* to 'dac19'@'%';
grant all privileges on dac20.* to 'dac20'@'%';
                        		    		
grant all privileges on dac21.* to 'dac21'@'%';
grant all privileges on dac22.* to 'dac22'@'%';
grant all privileges on dac23.* to 'dac23'@'%';
grant all privileges on dac24.* to 'dac24'@'%';
grant all privileges on dac25.* to 'dac25'@'%';
grant all privileges on dac26.* to 'dac26'@'%';
grant all privileges on dac27.* to 'dac27'@'%';
grant all privileges on dac28.* to 'dac28'@'%';
grant all privileges on dac29.* to 'dac29'@'%';
grant all privileges on dac30.* to 'dac30'@'%';
                                    
grant all privileges on dac31.* to 'dac31'@'%';
grant all privileges on dac32.* to 'dac32'@'%';
grant all privileges on dac33.* to 'dac33'@'%';
grant all privileges on dac34.* to 'dac34'@'%';
grant all privileges on dac35.* to 'dac35'@'%';
grant all privileges on dac36.* to 'dac36'@'%';
grant all privileges on dac37.* to 'dac37'@'%';
grant all privileges on dac38.* to 'dac38'@'%';
grant all privileges on dac39.* to 'dac39'@'%';
grant all privileges on dac40.* to 'dac40'@'%';
                                    
grant all privileges on dac41.* to 'dac41'@'%';
grant all privileges on dac42.* to 'dac42'@'%';
grant all privileges on dac43.* to 'dac43'@'%';
grant all privileges on dac44.* to 'dac44'@'%';
grant all privileges on dac45.* to 'dac45'@'%';
grant all privileges on dac46.* to 'dac46'@'%';
grant all privileges on dac47.* to 'dac47'@'%';
grant all privileges on dac48.* to 'dac48'@'%';
grant all privileges on dac49.* to 'dac49'@'%';
grant all privileges on dac50.* to 'dac50'@'%';
                                    
grant all privileges on dac51.* to 'dac51'@'%';
grant all privileges on dac52.* to 'dac52'@'%';
grant all privileges on dac53.* to 'dac53'@'%';
grant all privileges on dac54.* to 'dac54'@'%';
grant all privileges on dac55.* to 'dac55'@'%';
grant all privileges on dac56.* to 'dac56'@'%';
grant all privileges on dac57.* to 'dac57'@'%';
grant all privileges on dac58.* to 'dac58'@'%';
grant all privileges on dac59.* to 'dac59'@'%';
grant all privileges on dac60.* to 'dac60'@'%';




grant all privileges on dac1_CAMPUS.* to 'dac1'@'%';
grant all privileges on dac2_CAMPUS.* to 'dac2'@'%';
grant all privileges on dac3_CAMPUS.* to 'dac3'@'%';
grant all privileges on dac4_CAMPUS.* to 'dac4'@'%';
grant all privileges on dac5_CAMPUS.* to 'dac5'@'%';
grant all privileges on dac6_CAMPUS.* to 'dac6'@'%';
grant all privileges on dac7_CAMPUS.* to 'dac7'@'%';
grant all privileges on dac8_CAMPUS.* to 'dac8'@'%';
grant all privileges on dac9_CAMPUS.* to 'dac9'@'%';
grant all privileges on dac10_CAMPUS.* to 'dac10'@'%';
		 
grant all privileges on dac11_CAMPUS.* to 'dac11'@'%';
grant all privileges on dac12_CAMPUS.* to 'dac12'@'%';
grant all privileges on dac13_CAMPUS.* to 'dac13'@'%';
grant all privileges on dac14_CAMPUS.* to 'dac14'@'%';
grant all privileges on dac15_CAMPUS.* to 'dac15'@'%';
grant all privileges on dac16_CAMPUS.* to 'dac16'@'%';
grant all privileges on dac17_CAMPUS.* to 'dac17'@'%';
grant all privileges on dac18_CAMPUS.* to 'dac18'@'%';
grant all privileges on dac19_CAMPUS.* to 'dac19'@'%';
grant all privileges on dac20_CAMPUS.* to 'dac20'@'%';
                        		    		
grant all privileges on dac21_CAMPUS.* to 'dac21'@'%';
grant all privileges on dac22_CAMPUS.* to 'dac22'@'%';
grant all privileges on dac23_CAMPUS.* to 'dac23'@'%';
grant all privileges on dac24_CAMPUS.* to 'dac24'@'%';
grant all privileges on dac25_CAMPUS.* to 'dac25'@'%';
grant all privileges on dac26_CAMPUS.* to 'dac26'@'%';
grant all privileges on dac27_CAMPUS.* to 'dac27'@'%';
grant all privileges on dac28_CAMPUS.* to 'dac28'@'%';
grant all privileges on dac29_CAMPUS.* to 'dac29'@'%';
grant all privileges on dac30_CAMPUS.* to 'dac30'@'%';
                                    
grant all privileges on dac31_CAMPUS.* to 'dac31'@'%';
grant all privileges on dac32_CAMPUS.* to 'dac32'@'%';
grant all privileges on dac33_CAMPUS.* to 'dac33'@'%';
grant all privileges on dac34_CAMPUS.* to 'dac34'@'%';
grant all privileges on dac35_CAMPUS.* to 'dac35'@'%';
grant all privileges on dac36_CAMPUS.* to 'dac36'@'%';
grant all privileges on dac37_CAMPUS.* to 'dac37'@'%';
grant all privileges on dac38_CAMPUS.* to 'dac38'@'%';
grant all privileges on dac39_CAMPUS.* to 'dac39'@'%';
grant all privileges on dac40_CAMPUS.* to 'dac40'@'%';
                                    
grant all privileges on dac41_CAMPUS.* to 'dac41'@'%';
grant all privileges on dac42_CAMPUS.* to 'dac42'@'%';
grant all privileges on dac43_CAMPUS.* to 'dac43'@'%';
grant all privileges on dac44_CAMPUS.* to 'dac44'@'%';
grant all privileges on dac45_CAMPUS.* to 'dac45'@'%';
grant all privileges on dac46_CAMPUS.* to 'dac46'@'%';
grant all privileges on dac47_CAMPUS.* to 'dac47'@'%';
grant all privileges on dac48_CAMPUS.* to 'dac48'@'%';
grant all privileges on dac49_CAMPUS.* to 'dac49'@'%';
grant all privileges on dac50_CAMPUS.* to 'dac50'@'%';
                                    
grant all privileges on dac51_CAMPUS.* to 'dac51'@'%';
grant all privileges on dac52_CAMPUS.* to 'dac52'@'%';
grant all privileges on dac53_CAMPUS.* to 'dac53'@'%';
grant all privileges on dac54_CAMPUS.* to 'dac54'@'%';
grant all privileges on dac55_CAMPUS.* to 'dac55'@'%';
grant all privileges on dac56_CAMPUS.* to 'dac56'@'%';
grant all privileges on dac57_CAMPUS.* to 'dac57'@'%';
grant all privileges on dac58_CAMPUS.* to 'dac58'@'%';
grant all privileges on dac59_CAMPUS.* to 'dac59'@'%';
grant all privileges on dac60_CAMPUS.* to 'dac60'@'%';